manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi

  projects:
    # (Optional) you can remove this if you don’t intentionally use it as a module:
    - name: eyelash_corne
      url: https://github.com/a741725193/zmk-new_corne
      revision: main

    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    # NEW: pulls the dongle display module
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main

  self:
    path: config
